!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! nd2xyz. Copyright (C) Antonio Cammarata
! https://nano.cvut.cz/researchers/antonio-cammarata
! https://orcid.org/0000-0002-5691-0682
! 
! Converts an ND trajectory into xyz format
! 
! If used for production, you should cite
! A. Cammarata, M. Dasic, P. Nicolini, J. Chem. Phys. 161, 084111 (2024)
! https://doi.org/10.1063/5.0224108
!
!    This file is part of nd2xyz.
!
! This program is free software; you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation; either version 2 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License along
! with this program; if not, write to the Free Software Foundation, Inc.,
! 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! v. 0.7
! - routine variables changed according to the normal_to_cartesian routine
!   taken from pindol v. 1.13
!
! v. 0.6
! - the eigenvectors and frequencies are read from files qmatrix.nd and freq.nd
!   generated by qpoints v >= 1.3
!
! v. 0.5
! - the freq and qmatrix files are read in the format of qpoints v>=1.2
!
! v. 0.4
! - improved the skip of lines 
! - moved the check on the time step at the beginning of the do loops 
!   in the write routines
!
! v. 0.3
! added the option to write a POSCAR restart file using the last configuration
!
! v. 0.2
! added writing of accelerations
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Format of the input file
!
! char                  name of the POSCAR file
! char                  name of the ND trajectory file
! char                  name of the ND Qdot file
! char                  name of the ND Qddot file
! int                   number of atomic types (natom_types)
! char double           atomic symbol and mass (at_pertype(i), mass_pertype(i) [uma] of atom type 1
! ...  ...
! char double           atomic symbol and mass (at_pertype(i), mass_pertype(i) [uma] of atom type natom_types
! double double         time window: initial and final time
! flag                  1 = write POSCAR restart from last configuration
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

module var
  ! global parameters
  character(6), parameter :: progname = 'ND2XYZ'
  real(8), parameter :: uma_to_kg = 1.66053906660d-27     ! taken from NIST, 1 uma = 1.66053906660 x 10-27 kg
  real(8), parameter :: eV_to_J = 1.602176634d-19         ! taken from NIST, 1 e = 1.602176634 x 10-19 C 
  real(8), parameter :: eV_to_ieu = 1.d-10 * eV_to_J / uma_to_kg
  real(8), parameter :: internal_to_eVAng = 1.d0/eV_to_ieu ! internal energy units to eV/Ang
  character(3), parameter :: version='0.7'
  character(8), parameter :: error_string = ' ERROR: '
  ! from input
  integer, save :: nq_chk, natom_types, fl_last
  real(8), save :: t1, t2
  real(8), save, allocatable :: mass_pertype(:)
  character(2), save, allocatable :: at_pertype(:)
  character(256), save :: infile_q, infile_qd, infile_qdd
  ! from equilibrium UC
  integer, save :: atoms_UC, ncells(3), atoms_EC, ncells_tot
  integer, save, allocatable :: natoms_UC(:)
  real(8), save :: side_eq_UC(3,3), side_eq_EC(3,3)
  real(8), save, allocatable :: pos_eq_UC(:,:), mass_UC(:)
  real(8), save, allocatable :: pos_eq_EC(:,:,:)
  character(2), save, allocatable :: at_UC(:), at_EC(:,:)
  ! from qmatrix_*, freq_* 
  integer, save :: npG, npH, npS, npunique, nptot
  integer, save :: nq, npGq, npHq, npSq, npuniqueq, nptotq, npdiffq
  real(8), save, allocatable :: vec(:,:), vec_red(:,:)
  complex(8), save, allocatable :: eigen(:,:)
  ! delta
  real(8), parameter :: toldelta = 1.d-4

end module var

module functions
contains
  
  function i2a(i) result(out)
    character(:), allocatable :: out
    integer, intent(in) :: i
    character(range(i)+2) :: x

    write(x,'(i0)') i

    out = trim(x)
    
  end function i2a

  function f2a(f) result(out)
    character(20) :: out
    real(8), intent(in) :: f
    character(20) :: x

    write(x,'(f20.16)') f

    out = trim(x)
  end function f2a

end module functions

program nd2xyz
  use var, only: fl_last

  call init

  call read_eigen

  if ( fl_last /= 1) then

    call write_xyz
  
    call write_xdot
  
    call write_xddot

  else

    call write_last

  end if

  call deallocate_all
  call credits
  
  write(*,'(a)') ' Execution terminated.'
  write(*,*)

  stop
end program nd2xyz
