!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! phind. Copyright (C) Antonio Cammarata
! https://nano.cvut.cz/researchers/antonio-cammarata
! https://orcid.org/0000-0002-5691-0682
! 
! Phi for Normal Dynamics
! 
! Calculates the first order anharmonic interaction strength Phi(l,l',l'')
! to be used for the PINDOL code.
! The implemented selection rule is Delta(q+q'+q''); 
! the selection rules described in RSC Advances, 9, 37491 (2019)
! https://doi.org/10.1039/C9RA08294H
! are not implemented.
! Phi(l,l',l'') is not written for any triplet involving at least 
! one of the skip modes as specified in the header of freq.nd
!
! If used for production, you should cite
! Phys. Rev. B XX, XXXXX (XXXX)
! https://doi.org/10.1103/xxx
!
!    This file is part of phind.
!
! This program is free software; you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation; either version 2 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License along
! with this program; if not, write to the Free Software Foundation, Inc.,
! 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! v 4.3
! - the eigenvectors and frequencies are read from files qmatrix.nd and freq.nd
!   generated by qpoints v >= 1.4
! - new variables from pindol:
!   ! number of "unique" q-points (i.e. Gamma + set H + set S)
!   npG ! 0 or 1, if Gamma is present or not
!   npH ! number of points in the set H
!   npS ! number of points in the set S 
! - ! set auxiliary numbers of degrees of freedom for the normal dynamics
!   npGq = npG * nq
!   npHq = npH * nq
!   npSq = npS * nq
!
! v 4.2
! - the eigenvectors and frequencies are read from files qmatrix.nd and freq.nd
!   generated by qpoints v 1.3
! - the variable npoints in the subroutine read_eigen has been renamed 
!   to nunique for consistency with the PINDOL code v >= 1.9
! - fixed a bug (repeated elements) when printing phi.qallowed.nd
!
! v 4.1
! - the eigenvectors and frequencies are read from files qmatrix.nd and freq.nd
!   generated by qpoints v >= 1.2
! - removed the automatic skip of the first 3 or 6 Gamma modes: the label of
!   the acoustic and rotational modes in Gamma is read from the freq.nd file
! - removed the period_fl flag: if the system is periodic is accounted by the
!   values in the third line of the file freq.nd written by qpoints v 1.2
!
! v 4.0
! - eigenvectors and q-point vectors are read from qmatrix.dat and freq.dat
!   generated by qpoints v >= 1.1
! - complex conjugated eigenvectors and freq files are not written any more
! - the number of q-points is read from qmatrix.dat file
! - phi elements are written according the specific order as in calc_double_sum_phi
!   routine of the ND code
! - added header in phi.nd with md5sum of qmatrix and freq files
!
! v 3.9
! - removed the routines which calculate the triangular and full tensor
! - the tensor map is only available for the triangular and the unique phi form
! - the complex conjugated eigenvectors are calculated on the fly
! - the code assumes to work with the set Gamma+S; added a loop in read_eigen
!   to check if there is no element of S*
! - the Delta(q+q'+q'') allowed transitions are written into a file
!
! v 3.6
! - fixed compatibility issues with ND code
! - the calc_np routine has been simplified for a faster computation
! - restructured the input file
! - calc phi options have been added; the calc routines changed accordingly
!
! v 3.5
! - Corrected bugs in the delta selection rules
!
! v 3.4
! - Delta(q+q'+q'') is calculated by checking the components of q+q'+q''
! - This version is meant to be used with qpoints v >= 1.0
!   so the q-vector components are not multiplied by 2pi at the end of
!   the freq* files reading (see the end of read_eigen.f90 and read_eigennn.f90
!   files)
!
! v 3.3
! - only one element of each complex conjugated couple is written for
!   phinn_fl=1
!
! v 3.2
! - added the possibility to write only the non-null elements of the upper
!   triangular part
! - added flag to select non-periodic system to neglect rotational
!   modes
!
! Antonio Cammarata
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Format of the input file
!
! char                  name of the POSCAR file
! int int int           dimensions of the supercell used to create fc3.dat (ncells(i))
! int                   number of atomic types (natom_types)
! char double           atomic symbol and mass (at_pertype(i), mass_pertype(i) [uma] of atom type 1
! ...  ...
! char double           atomic symbol and mass (at_pertype(i), mass_pertype(i) [uma] of atom type natom_types
! int                   write (q,j -> l) map: 0=no, 1=yes
! int                   calc phi: 0=no, 1=yes
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

module var
  ! global parameters
  character(3), parameter :: version='4.3'
  character(5), parameter :: progname = 'PHIND'
  ! from input
  integer, save :: natom_types
  integer, save :: phical_fl, phimw_fl
  real(8), save, allocatable :: mass_pertype(:)
  character(2), save, allocatable :: at_pertype(:)
  ! from equilibrium UC
  integer, save :: atoms_UC, nq, ncells(3), atoms_EC, ncells_tot
  integer, save, allocatable :: natoms_UC(:)
  real(8), save :: side_eq_UC(3,3), side_eq_EC(3,3)
  real(8), save, allocatable :: pos_eq_UC(:,:), mass_UC(:)
  real(8), save, allocatable :: pos_eq_EC(:,:,:)
  character(2), save, allocatable :: at_UC(:), at_EC(:,:)
  ! from qmatrix_*, freq_* and fc3
  integer, save ::  nskip, npunique, npG, npH, npS, nptot, npGq, npHq, npSq
  integer, save, allocatable :: skipmod(:,:)
  real(8), save, allocatable :: vec(:,:)
  complex(8), save, allocatable :: eigen(:,:)
  type vec_red_s
    real(8) :: ei(3)
    character :: set
  end type
  type (vec_red_s), save, allocatable :: vec_red(:)
  ! delta
  real(8), parameter :: toldelta = 1.d-4
  integer, save, allocatable :: delta(:,:)
  integer(8), save :: ll
  ! calc_phiun, phi_reorder
  type phi_tensor
    integer :: kk(3)
    real(8) :: el(2)
  end type
  type (phi_tensor), save, allocatable :: phi(:)

end module var

module integer_to_string
contains
  function i2a(i) result(out)
    character(:), allocatable :: out
    integer, intent(in) :: i
    character(range(i)+2) :: x

    write(x,'(i0)') i

    out = trim(x)
    
  end function i2a

  function i82a(i) result(out)
    character(:), allocatable :: out
    integer(8), intent(in) :: i
    character(range(i)+2) :: x

    write(x,'(i0)') i

    out = trim(x)
    
  end function i82a

end module integer_to_string

program phind
use var, only: phical_fl, phimw_fl

  call init

  call read_eigen

  call calc_delta

  select case (phical_fl)
    case (1)
      call calc_phiun
      call reorder_phi
  end select

  if ( phimw_fl == 1 ) then
    call write_map
  end if

  call deallocate_all
  call credits
  
  write(*,'(a)') ' Execution terminated.'
  write(*,*)

  stop
end program phind
